/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Sage.
 *
 * The Initial Developer of the Original Code is
 * Peter Andrews <petea@jhu.edu>.
 * Portions created by the Initial Developer are Copyright (C) 2005
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 * Peter Andrews <petea@jhu.edu>
 * Erik Arvidsson <erik@eae.net>
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */
 
#include "nsISupports.idl"
#include "sageIFeedItem.idl"

[scriptable, uuid(28C949A0-57A4-4825-A5FF-2C72E688EAF8)]
interface sageIFeed: nsISupports {

  // sort order constants     
  const unsigned short SORT_SOURCE = 0x00;
  const unsigned short SORT_CHRONO = 0x01;

  void init(in AString title, in AString link, in AString description, in AString author, in AString feedURI, in AString format);
  
  void addItem(in sageIFeedItem item);
  
  PRBool hasFeedURI();
  AString getFeedURI();
  void setFeedURI(in AString feedURI);
  
  AString getTitle();

  PRBool hasDescription();
  AString getDescription();
  
  AString getLink();
  
  PRBool hasAuthor();
  AString getAuthor();

  PRBool hasLastPubDate();
  PRTime getLastPubDate();

  PRInt32 getItemCount();
  
  sageIFeedItem getItem(in PRInt32 index);
  
  void setSort(in unsigned short order);
  
  AString getFormat();
  
  AString getSignature();

};